services:
  hbbs:
    image: ghcr.io/sistemskaadministracija-cell/inforiaconnect-server@sha256:2a029367efd204ed78f35d8a6e6707cd36c3a4a8dce6af77e1cba173cbd217c7
    container_name: hbbs
    network_mode: host
    command:
      - /usr/bin/hbbs
      - -r
      - connect.inforia.si:21117
      - -k
      - _
      - --blocked-ids-file
      - /root/blocked_ids.txt
    volumes:
      - /home/inforiaadmin/rustdesk:/root
    restart: always

  hbbr:
    image: ghcr.io/sistemskaadministracija-cell/inforiaconnect-server@sha256:2a029367efd204ed78f35d8a6e6707cd36c3a4a8dce6af77e1cba173cbd217c7
    container_name: hbbr
    network_mode: host
    command:
      - /usr/bin/hbbr
      - -k
      - _
    volumes:
      - /home/inforiaadmin/rustdesk:/root
    restart: always
